version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8080"
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
      - ./alembic.ini:/app/alembic.ini
      - ./app_database.db:/app/app_database.db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    env_file:
      - .env
