"""add_sources_and_codes_to_messages

Revision ID: 3bfcbf41f62a
Revises: 9aeaa988a58e
Create Date: 2025-08-22 15:58:35.896308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfcbf41f62a'
down_revision = '9aeaa988a58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sources', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('codes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'codes')
    op.drop_column('messages', 'sources')
    # ### end Alembic commands ###
