"""Add table_data and charts to messages

Revision ID: 4fad5ba89a77
Revises: 3bfcbf41f62a
Create Date: 2025-08-27 15:33:53.167247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fad5ba89a77'
down_revision = '3bfcbf41f62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('table_data', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('charts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'charts')
    op.drop_column('messages', 'table_data')
    # ### end Alembic commands ###
