"""add sendertype

Revision ID: 14643d3f70e1
Revises: 983c29b7f0d6
Create Date: 2025-08-11 16:05:27.599570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14643d3f70e1'
down_revision = '983c29b7f0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('messages', sa.Column('sender_type', sa.String(), nullable=True))

    # Update existing records with a default value
    op.execute("UPDATE messages SET sender_type = 'user' WHERE sender_type IS NULL")

    # Now alter the column to be not nullable
    op.alter_column('messages', 'sender_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_type')
    # ### end Alembic commands ###
